name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login Docker Hub
      run: echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u kkkqwerasdf123 --password-stdin
      env:
        DOCKERHUB_ACCESS_TOKEN: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}
    - name: Build the Docker image
      run: docker buildx build --platform=linux/amd64,linux/arm64 --file Dockerfile -t kkkqwerasdf123/jenkins:latest --push .
